#! /bin/bash 

echo "Enter filename to print from awk"
read filename 

if [ -f $filename ]
then 
	awk '{print}' $filename 

else 
	echo "File doesn't exist"
fi 


#! /bin/bash 

echo "Enter the filename to print from awk"
read filename 

if [ -f $filename ]
then

	awk '/string/ {print}' $filename 

else 
	echo "$filename doesn.t exist"
fi 


#! /bin/bash 

echo "Enter the filename to print from awk"
read filename 

if [ -f $filname ]
then 
	awk '/string/ {print $1,$3}' $filename 

else 
	echo "$filename doesn/t exist"
fi 



echo "Enter the filename to print from awk"
read filename 

if [ -f $filname ]
then 
	awk '/string/ {print NF}' $filename 

else 
	echo "$filename doesn/t exist"
fi 





