#! /bin/bash 

url="http://speedtest.ftp.otenet.gr/files/test10Mb.db"
curl ${url} -O


#! /bin/bash 

url="http://ipv4.download.thinkbroadband.com/20MB.zip"
curl ${url} >> FileDw


#! /bin/bash 

url="http://ipv4.download.thinkbroadband.com/20MB.zip"
curl -I ${url} 


