#! /bin/bash 

echo "enter 1st string"
read s1

echo "enter 2nd string"
read s2

if [ "$s1" == "$s2" ]
then
	echo "sting match"
else
	echo "string don't match"
fi 


#! /bin/bash 

echo enter 1st input
read p1

echo enter 2nd input
read p2 

if [ $p1 == $p2 ]
then 
	echo "done"
else
	echo "undone"
fi


#! /bin/bash 

echo "enter 1st string" 
read s1

echo "enter 2nd string"
read s2

if [ "$s1" \> "$s2" ]
then 
	echo "$s1 is greater than $s2"
elif [ "$s1" \< "$s2" ]
then 
	echo "$s2 is greater than $s1"
else
	echo "both are equal"
fi 


#! /bin/bash 

echo "enter 1st string" 
read s1

echo "enter 2nd string"
read s2

if [ "$s1" \> "$s2" ]
then 
	echo "$s1 is greater than $s2"
elif [ "$s1" \< "$s2" ]
then 
	echo "$s2 is greater than $s1"
else
	echo "both are equal"
fi 


#! /bin/bash 

echo "enter 1st string"
read j1

echo "enter 2nd string"
read j2

c=$j1$j2

echo $c


#! /bin/bash 

echo "enter 1st string"
read j1

echo "enter 2nd string"
read j2

c=$j1$j2

echo $c


#! /bin/bash 

echo "enter the 1st string"
read j1 

echo "enter the 2nd string"
read j2 

echo ${j1^}
echo ${j1^^}


#! /bin/bash

echo "enter 1st string"
read j1 

echo "enter 2nd string"
read j2 

echo ${j1^}
echo ${j2^^}














